### ISSUE TITLE
https://online.anyflip.com/emyuk/qiic/mobile/

### ISSUE THREAD

**Issue by Nalinrat8364** [AlimulK/anyflip-dl#1]

**Comment by AlimulK** [comment]
Not sure what your issue is but the book downloaded just fine for me

<img src="https://github.com/user-attachments/assets/b3ed53f1-dfbb-4026-8e22-4848dd993075" width="400">

<img src="https://github.com/user-attachments/assets/f2ae5880-141e-4e7d-ad03-f33c7ae1e966" width="400">

You can rename it to whatever you want

<img src="https://github.com/user-attachments/assets/58c214a7-c935-4927-afe0-d5f58d71e28c" width="400">
